name: Deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main

env:
  FLASK_ENV: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Database Directory
      run: |
        mkdir -p instance
        touch instance/site.db
        chmod -R 777 instance
        chmod 666 instance/site.db

    - name: Create .env file
      run: |
        echo "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" >> .env
        echo "AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}" >> .env
        echo "DEPLOYMENT_NAME=${{ secrets.DEPLOYMENT_NAME }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "FLASK_ENV=production" >> .env

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EGPT'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'